# Generated by Django 4.2.5 on 2023-09-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='address',
            field=models.CharField(default='Cairo, Egypt', max_length=200),
        ),
    ]
