# Generated by Django 4.2.5 on 2023-10-13 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_newsletter_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 10, 13, 11, 17, 17, 336632, tzinfo=datetime.timezone.utc)),
        ),
    ]
